### ISSUE TITLE
Unable to connect to Orient DB

### ISSUE THREAD

**Issue by pvjpavankumar** [epfldata/dbstage#1]
We tried to connect to Orient DB 3.0.21 and its respective driver via DBStage application, but it always throw an error that it is unable to connect. We tried the same JAR file using Java class and were able to connect.

**Comment by LPTK** [comment]
Hello, thanks for your interest in this project. However, this is only a work-in-progress prototype. It is absolutely not meant to be used right now. In particular, dbStage is _not_ meant to connect to external databases.
If you are looking for Scala libraries to work with external databases, please see, for example, [this](https://www.reddit.com/r/scala/comments/ce1y07/database_libraries_in_2019/).

**Comment by pvjpavankumar** [comment]
Ok, thanks for the information.
